# Generated by Django 3.0.7 on 2020-06-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200604_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[['n', 'New'], ['w', 'In work'], ['c', 'Completed']], default='n', help_text='Current task status', max_length=1),
        ),
    ]
