version: '3.8'

services:
    web:
        build: 
            context: ./tt_project
            dockerfile: Dockerfile.prod
        restart: always
        entrypoint:
            - /home/app/web/entrypoint-tasktable.prod.sh
        command: gunicorn tasktable.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        expose:
            - 8000
        env_file:
            - ./env.prod
        depends_on:
            - db
            - rabbitmq
            - redis
        networks:
            - net_inner

    db:
        image: postgres:12.0-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./env.db
        networks:
            - net_inner

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        ports:
            - 1337:80
        depends_on:
            - web
        networks:
            - net_inner

    rabbitmq:
        image: rabbitmq:3.8.6-management-alpine
        restart: always
        volumes:
            - ./rabbitmq-data/:/var/lib/rabbitmq/
        networks:
            - net_inner

    redis:
        image: redis:6.0.6-alpine
        volumes:
            - ./redis-data/:/data/
        networks:
            - net_inner

    worker_default:
        build: ./tt_project
        restart: always
        entrypoint:
            - /home/app/web/entrypoint-celery-worker-default.sh
        env_file:
            - ./env.prod
        depends_on:
            - db
            - rabbitmq
            - web
        volumes:
            - ./tt_project/:/home/app/web/
        networks:
            - net_inner

    celery_beat:
        build: ./tt_project
        restart: always
        entrypoint:
            - /home/app/web/entrypoint-celery-beat.sh
        env_file:
            - ./env.prod
        depends_on:
            - db
            - rabbitmq
            - web
        volumes:
            - ./tt_project/:/home/app/web/
        networks:
            - net_inner

    flower_dashboard:
        build: ./tt_project
        restart: always
        entrypoint:
            - /home/app/web/entrypoint-celery-flower.sh
        ports:
            - 5555:5555
        env_file:
            - ./env.prod
        depends_on:
            - web
            - rabbitmq
            - worker_default
        volumes:
            - ./tt_project/:/home/app/web/
        networks:
            - net_inner

volumes:
    postgres_data:
    static_volume:
    media_volume:

networks:
    net_inner:
        driver: bridge
