version: '3.8'

services:
    web:
        build: ./tt_project
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./tt_project/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./env.dev
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=tasktable
            - POSTGRES_PASSWORD=tasktable
            - POSTGRES_DB=tasktable_dev

volumes:
    postgres_data:
