# Generated by Django 3.0.5 on 2020-06-01 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200601_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='performer',
        ),
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.ManyToManyField(related_name='task_performer', to=settings.AUTH_USER_MODEL),
        ),
    ]
