# Generated by Django 3.0.7 on 2020-06-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200605_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'New'), ('w', 'In work'), ('c', 'Completed')], default='n', help_text='Current task status', max_length=1),
        ),
    ]
